### ISSUE TITLE
in clipboard_linux.cpp using xclip copy should not create a newline  

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#10]
I have commited a change in my branch from echo to echo -n which will fix this issue.

**Comment by leecbaker** [comment]
Man, I wish I had seen this before the release last night. Just added the -n in 4493b25.

**Comment by sparker256** [comment]
Lee Is there some reason you have not pulled my save preferences to disk? I have been using it for over a month with no issue and I keep re-syncing to your changes but it is never pulled.

**Comment by leecbaker** [comment]
Hi Bill,
Sorry about just letting this PR sit- I really should have mentioned some of this earlier:
* There's code in there for linux clipboard stuff, for storing window position and that changes the log. It's best if these can be in multiple pull requests.
* Some of the lines aren't consistent with the indentation of the rest of the file, mixing tabs and spaces (example https://github.com/leecbaker/datareftool/pull/5/files#diff-344da0a5301dedc9a87d341ab1993176L104 ). This is bad style.
* I have a more comprehensive JSON-based preferences system in development that handles multiple windows as well as preferences other than the windows position. Honestly, It's pretty unlikely that I'll merge in the preferences code because of this.
* In the clipboard code, the existing code works right? What's the purpose of the changes that you've made? I really try to avoid calling external commands if possible (i.e. popen() or system()), and strongly prefer code that doesn't do that.

**Comment by sparker256** [comment]
Hi Lee,

Not harsh at all just the feedback I was waiting for. 

On the one pull request I was just trying to keep my code in line with your changes and github said "This pull request can be automatically merged by project collaborators" so thought I was doing the right thing. 

On the changes to the log what I was trying to do is always know that if DRT put something there we know that and would not have to guess.

There seems to be a issue where on my Linux machine the formatting look fine and consistent to but when it gets on github does not and will look into why that is true. I will look at your example and try to do better in the future.

Sounds great on your  comprehensive JSON-based preferences system  and will await its arrival.

On the Linux clipboard yes the existing does work but you had asked if we could use xclip for both copy and paste and that is what I did.
