### ISSUE TITLE
Some aircraft use brackets in datarefs and we are not looking for them

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#20]
We are not looking for brackets in many aircraft files and missing many datarefs. I have a patch to add support for brackets.
[sparker256_brackets_patch.diff.zip](https://github.com/leecbaker/datareftool/files/746525/sparker256_brackets_patch.diff.zip)

**Comment by leecbaker** [comment]
Hi Bill, thanks so much for the patch, and sorry for taking so long to review this.

It kind of surprises me that people would use brackets in data ref names, since data refs + brackets usually mean access into an array dataref. Is there an example of an aircraft that does this? Is this a common issue?

Second question, does this create a problem for array data refs that we detect from, e.g. OBJ files? For instance, if a obj file reference a dataref like `sim/cockpit2/switches/instrument_brightness_ratio[0]`, do we expect that that is a data ref with name `sim/cockpit2/switches/instrument_brightness_ratio` which is an array, and we access element 0, or is it a scalar data ref with the name `sim/cockpit2/switches/instrument_brightness_ratio[0]`? (I found that particular data ref name in `X-Plane 10/Aircraft/General Aviation/Cessna 172SP/Cessna_172SP_cockpit.obj:13177`)

I guess one possible solution here is to try to open the data ref without brackets using `XPLMFindDataRef()`, and if that returns `NULL`, then we can try opening the same data ref assuming the brackets are included in the name.

**Comment by sparker256** [comment]
Hi Lee,

I have found at least two aircraft but there may be more. The Thranda Kodiak and the Dreamfoil EaMB-110 both use brackets in there datarefs.

I have not seen any bad side effect of my change with array datarefs.

If it would help I can provide some screen shots of DataRefTool showing bracket datarefs and array datarefs if that would help.

**Comment by leecbaker** [comment]
I'll go ahead and put a change in to work with those aircraft; at this point, I'm just a bit surprised that somebody would name their datarefs like that when it so obviously conflicts with the syntax for array datarefs.

Just curious, what do the names look like for the bracket datarefs you've found?

**Comment by sparker256** [comment]
Here is a couple of examples.
![datareftool_thranda_dreamfoil_emb110_brackets](https://cloud.githubusercontent.com/assets/1274225/23772029/7a421586-04e7-11e7-93ad-eb61d8f1059d.jpg)
![datareftool_thranda_quest_kodiak_brackets](https://cloud.githubusercontent.com/assets/1274225/23772038/7f507c52-04e7-11e7-9134-f7a722cc416d.jpg)

**Comment by sparker256** [comment]
This seems to be fixed so will close it to help clean up the issue list.

**Comment by leecbaker** [comment]
Glad to hear that is seems to be fixed.
