### ISSUE TITLE
Reloading Plugins with Datareftool do crash my sim

### ISSUE THREAD

**Issue by Forsaken-Player** [leecbaker/datareftool#34]
Hi, 
As the title says. If I hit reload plugin once, it pops up a windows telling me that I should move the new plugin to the resources/plugin and everything works ok. Now if I do it once more (at the second time) x-plane.exe process gets unresponsive.
![datareftoolissue1](https://user-images.githubusercontent.com/13246441/44557006-e51e0580-a712-11e8-91c9-21c283250b8a.JPG)

**Comment by leecbaker** [comment]
Hi @Forsaken-Player, there can be tons of causes of this. Many plugins don't work correctly with the reload plugin functionality for one reason or another, and that's not something I can fix.

Closing as not fixable.

**Comment by leecbaker** [comment]
One more thing- can you check your Log.txt? It might have more information on if a plugin is causing the crash.

**Comment by alist** [comment]
Hi @leecbaker, do you have any advice for someone to make their plugin work correctly with "Reload plugins"-- our plugin used to work, but now (and I can't tell if it's because of an XPlane 12 beta we started running) it does not.... We get the "still in use" error out of windows. Are there certain xplane plugin lifecycle hooks we need to respect, or does having a secondary thread running lead to issues as well? Thank you.
