### ISSUE TITLE
total noob

### ISSUE THREAD

**Issue by fpuentegomez** [leecbaker/datareftool#57]
Hello, total noob here,
I have downloaded the source code, extracted, created build directory and compiled as per the instructions.
Then I copied the folder datareftool (located inside bin) to the XP10/Resources/plugins folder.
Datareftool doesn't show up in the plugins list.
Is there something that I am doing wrong?
Thanks in advance,
Federico

**Comment by leecbaker** [comment]
Hi Federico,

1. The current version of DRT doesn't support X-Plane 10 because it uses newer APIs. It may be possible to compile a version for XP10, but I haven't tried myself. You'll need to change some of the [defines in this file](https://github.com/leecbaker/datareftool/blob/5a43f2cd88783f1aa934e05779090a34200180ee/src/CMakeLists.txt#L87) (XPLM301, etc).

2. Make sure your XPL is in the [proper location](https://developer.x-plane.com/article/building-and-installing-plugins/). Most people are using the XPLM 2.1 file layout.

3. If the plugin doesn't load, look at the Log.txt file for an explanation. If it's in the right place, there will be an entry in the Log.txt file with an explanation.

**Comment by leecbaker** [comment]
I've just committed the changes so that you can compile for X-Plane 10. DRT should support X-Plane 10 now IF you make the necessary changes to the CMakeLists.txt described above.

Feel free to re-open this if DRT doesn't compile or function in X-Plane 10 for some reason.
