### ISSUE TITLE
Just changed some weather dataref and bang, all weather layers disappear

### ISSUE THREAD

**Issue by willschubert1977** [leecbaker/datareftool#66]
Hi guys!

I'm having this issue with one script I created to add turbulence on weather layers, and now tried to do some tests with datareftool, but having same freak issue. I posted this video bellow. The thing is: Any (Weather) dataref I change, suddenly all weather layers is clean!  Anyone have any idea what is going on? (All other datarefs, no problem, I can turn lights on/off, change lights brightness, etc...)

XP11, Ubuntu 20.4

SHORT VIDEO => https://youtu.be/qNP-5bpVUQw

**Comment by leecbaker** [comment]
Hi,

Honestly I don't know much about the weather system. This looks like an issue with X-Plane itself, rather than DRT. I'd suggest asking about it on the [X-plane.org forums](https://forums.x-plane.org/index.php?/forums/forum/23-x-plane-developers-and-plugins/), or if it really looks like a bug, use the [X-Plane bug reporter.](https://dev.x-plane.com/support/bugreport.html)

I'm closing this issue since it sounds like your issue isn't with DRT itself; good luck finding a solution!
