### ISSUE TITLE
Dat/Com/D+C button issue after plugins reloading

### ISSUE THREAD

**Issue by DrGluck** [leecbaker/datareftool#68]
How to reproduce:
1. Dataref window state
![Cessna_172SP - 2020-12-25 13 32 39](https://user-images.githubusercontent.com/4846443/103132628-87b96b00-46b6-11eb-8c00-d1cb5e892da4.png)
2. Reload the plugins. ( BTW, there is another bug: shortcuts are not working )
3. Looks like Dat/Com/D+C button is in a wrong state:
![Cessna_172SP - 2020-12-25 13 33 03](https://user-images.githubusercontent.com/4846443/103132690-fac2e180-46b6-11eb-9853-686aee2e81c7.png)

**Comment by leecbaker** [comment]
@DrGluck , thanks for this bug report. I knew something weird was happening occasionally with dataref filtering, but it turns out to only happen when DRT finds new datarefs, and a search has already been made. (Reloading the plugin is one of these situations- the search is restored immediately, but datarefs are found after that, as they are scanned in the background.)

I've fixed this in 494602023f21e747b41c04e9c7b54e5eb14d8652, and have released a new version that includes this fix. If you see this bug again, please re-open this issue or create a new one.
