### ISSUE TITLE
Some keyboard shortcuts are not working

### ISSUE THREAD

**Issue by DrGluck** [leecbaker/datareftool#69]
I haven't checked all the options, but the following shortcuts do not work for me:
1. Reload plugins
2. Reload aircrafts
3. Open a new search window

**Comment by Avacee** [comment]
Same here but I assume it's because the previous release "2020_03_23" created custom commands called **datareftool/command_name** whereas release "2020_12_24" creates custom commands called **leecbaker/datareftool/command_name** or **leecbaker/datareftool/prefs/command_name**  
Hence the previous keyboard mappings are no longer valid.
If DRT was meant to create some default key mappings then there appears to be a bug.

A quick trip to Settings -> Keyboard -> leecbaker ->datareftool to re-add them worked for me.

**Comment by DrGluck** [comment]
I've tried removing the previous settings. But it still didn't help.

**Comment by leecbaker** [comment]
@Avacee is completely correct. When I rewrote this part of DRT, I inadvertently changed the names of the existing commands. Since people are already using the new version of DRT, I can't really change them back.

At this point, my recommendation is to simply create new keyboard mappings as @Avacee describes.

**Comment by DrGluck** [comment]
I don't know why, but hotkeys still doesn't work.
I removed dataref keys from the "\X-Plane 11\Output\preferences\X-Plane Keys.prf" file. Then I add this line:
"H <NONE> leecbaker/datareftool/reload_aircraft Reload the current aircraft"
But still nothing.

BTW, I tried X-Plane 11.51r1, then X-Plane 11.41r1, then X-Plane 10.51r2 (xp10 version of the plugin)

Can I check something else?
