### ISSUE TITLE
Problems with a text type comparison

### ISSUE THREAD

**Issue by Lorsand** [leecbaker/datareftool#70]
Hello! Congratulations on the job, it's fantastic, it has opened my eyes to a new world with this tool.

I wanted to ask you how I can do a text comparison, since I am making a custom xchecklist for the Zibo, and I want to compare two text fields, but I can't find the way. I'm not a computer scientist, just a hobbyist.

These fields are:
laminar / B738 / irs / gps_pos = laminar / B738 / irs / irs_pos_set

I've been looking at the Xcheckist manual but can't find a way to compare these two text fields.

I would be grateful for any help. Thank you!

**Comment by leecbaker** [comment]
Hi @Lorsand , since this issue has to do with Xchecklist's functionality rather than DRT, I'd advise you to direct your question towards the folks who make Xchecklist.

@sparker256, who makes Xchecklist, told me that what you're trying to isn't a supported function of Xchecklist. He would be the best person to contact with any future questions about functionality.

I'm closing this issue since the questions are more about X-checklist than DRT.

**Comment by Lorsand** [comment]
Hi @leecbaker, thanks anyway!
