### ISSUE TITLE
Hotkeys don't work on Windows 

### ISSUE THREAD

**Issue by DrGluck** [leecbaker/datareftool#72]
Hi, Lee! Sorry to do this again, but i'm pretty sure that hotkeys don't work on Windows. I checked it on two PCs, and my friends checked it too.
The problem is that your plugin call XPLMCreateCommand, but never calls XPLMRegisterCommandHandler. I ckecked this with debugger, look at the picture. I put a breakpoint on XPLMRegisterCommandHandler. Your plugin never calls it. 
![Скриншот 2021-01-31 15 43 50](https://user-images.githubusercontent.com/4846443/106384471-0ef7ae00-63dc-11eb-9512-070153405282.png)
This is the code from CommandProvider constructor:
```
cr = XPLMCreateCommand(name.c_str(), description.c_str());
    
    if(bool(begin_func)) {
        XPLMRegisterCommandHandler(cr, CommandProvider::begin_handler, 1, static_cast<void *>(this));
    }

    if(bool(continue_func)) {
        XPLMRegisterCommandHandler(cr, CommandProvider::continue_handler, 1, static_cast<void *>(this));
    }

    if(bool(end_func)) {
        XPLMRegisterCommandHandler(cr, CommandProvider::end_handler, 1, static_cast<void *>(this));
    }
```
For unknown reason all three "if" statements always false. I really don't know why "if(bool(begin_func))" is failed, but its happens. 
It seems like lambda functions are always empty.

**Comment by DrGluck** [comment]
Now it's working. Thanks!

**Comment by leecbaker** [comment]
Glad to hear that it's working. @DrGluck If you're wondering why it wasn't working, there are identically named constructor parameters and member variables (like `begin_func`). The constructor moves the values of these variables from the parameters into the member variables, but the way std::move works, once they are moved, the parameters technically have an undefined state, and may be true or false, because what's actually in these variables is undefined.

Best practice here IMO would be to not use the same variable names (which warning `-Wshadow` would catch), and clang's UBSan might be able to detect this specific problem.
